name: Correzione documentazione
description: Segnala un` errore documentazione 
title: '[Nome del doc] - [sezione da modificare]'
labels: ["documentation","P1"]
projects: ['AndreaSoranzo/pp']

body:
  - type: textarea
    id: fix
    attributes:
      label: Breve descrizione
      description: |
      Breve descrizione di cosa andare a correggere e come

      Tip: Usa la sintassi di Markdown per inserire la lista di checkbox se vuoi fare una lista
    validations:
      required: true
