
name: To-Do Documentazione
description: Crea e assegna un task riguardante la documentazione 
title: 'To-Do: [Nome_documento] - [sezione]'
labels: 'documentation'
projects: 'AndreaSoranzo/5'

body:
  - type: input
    id: obj-disc
    attributes:
      label: Oggetto di discussione
      description: Inserisci il verbale nel quale si è discusso di aggiungere questa sezione
      placeholder: Nome di verbale interno o esterno
    validations:
      required: false
  - type: textarea
    id: list
    attributes:
      label: Informazioni minime da implementare
      description: |
        Elenca le cose più importanti da implementare
      
        Tip: Usa la sintassi di Markdown per inserire la lista di checkbox
      placeholder: "- [ ] Item 1"
    validations:
      required: true