name: Check backend code

on:
  pull_request:
    branches:
      - 'code/backend-**'
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '3Dataviz/backend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: 3Dataviz/backend

      - name: Check format
        run: npx prettier --check .
        working-directory: 3Dataviz/backend

      - name: Run lint
        run: npm run lint
        working-directory: 3Dataviz/backend

      - name: Run tests
        run: npm test
        working-directory: 3Dataviz/backend

      - name: Build
        run: npm run build
        working-directory: 3Dataviz/backend