name: Check frontend code

on:
  pull_request:
    branches:
      - 'code/frontend'
      - main
      
jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "3Dataviz/frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: 3Dataviz/frontend

      - name: Check format
        run: npx prettier --check .
        working-directory: 3Dataviz/frontend

      - name: Run lint
        run: npm run lint
        working-directory: 3Dataviz/frontend

      - name: Run tests
        run: |
          if [ -n "$(find . -name '*.test.*' -print -quit)" ]; then
            npm test
          else
            echo "No tests found, skipping."
          fi
        working-directory: 3Dataviz/frontend

      - name: Build
        run: npm run build
        working-directory: 3Dataviz/frontend
